name = "runviz-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
FRONTEND_URL = "https://hwong103.github.io/runviz"
ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImJmOWFiMWY1N2JmODQzNTRiN2YxMjRiNjBmZWFhZGU2IiwiaCI6Im11cm11cjY0In0="

[[kv_namespaces]]
binding = "TOKENS"
id = "30c9eb9422124409935de1f20bb28237"

# For local development, create a preview namespace
# [[kv_namespaces]]
# binding = "TOKENS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-id"
